services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./src/Dockerfile
    working_dir: /src
    volumes:
      - ./src:/src
    tty: true
    stdin_open: true
    command: bash
